### ISSUE TITLE
Huge delays on GROUP REPEAT

### ISSUE THREAD

**Issue by eshutoff** [enketo/enketo-website#57]
Hi,
**last 4-5 months** we experienced the issue with “group repeat” on Kobo and Ona, they use your service, so I think the problem is here. Tested in different browsers, even MS IE lol.
After 15 iterations of group repeat, every next opened with progressive delay, 25, 45, 90, 200 sec an so on. Just frozen page, scroll doesn’t work.
The issue doesn’t relay to complexity of group, the group with only one question has the same problem.
I tried to ask help of Kobo and Ona and ODK teams but still no success. 

Looking for your advice, guys, I like ODK and Enketo, but that is real problem for users!

Best wishes, Eugene

**Comment by MartijnR** [comment]
Thanks for the report! I've added your report to an existing report here: https://github.com/kobotoolbox/enketo-express/issues/806 (The application that Ona and KoBo use is called enketo-express).
