### ISSUE TITLE
Geolocation capture issue

### ISSUE THREAD

**Issue by shreyakesar** [enketo/enketo-website#80]
In case we want to capture current GPS location in enketo forms, then the latitude and longitude field being editable dilutes the capturing of current location as it can be modified by the person submitting the form.
Is there any way to make the GPS coordinates non editable

**Comment by MartijnR** [comment]
Not yet, but some day we will (be able to use a calculation without user input). There is a spec for it.

Until then, the best you can do is use the appearance 'hide-input'.

**Comment by shreyakesar** [comment]
How to use the appearance hide input?

**Comment by shreyakesar** [comment]
Got it.
Thanks for the input!
