### ISSUE TITLE
Update enketo-core dependency in overview page

### ISSUE THREAD

**Issue by FrankApiyo** [enketo/enketo-website#91]
Since `enketo-xpathjs` has been replaced by `openrosa-xpath-evaluator` in enketo-core. Should this here be replaced to point to the new dependency? https://github.com/enketo/enketo-website/blob/12d41ea3f8185d64b6fd96b977580fe7115c0cc2/src/views/develop/index.pug#L36

If this should change, I'd be glad to make a PR.

Thanks.

**Comment by FrankApiyo** [comment]
seems this change was reverted

**Comment by MartijnR** [comment]
Thanks Frank!

It will come back soon so it's good to leave this open. I was just doing some initial testing and collecting some performance data on https://github.com/enketo/enketo-core-performance-monitor.
